language: php
php:
- 7.0
script:
- php -l *.php
branches:
  only:
  - "/\\d\\.\\d\\.\\d/"
deploy:
  provider: script
  script: sh deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=http://plugins.svn.wordpress.org/gutenipsum/
  - secure: "lqo28hb55i3k6HxOtSmtzB8MD75vY/xMzryyx2Z9u8pxufMDIdT6rRrHI3N+3/WATNOU5xjd64nCFkDitwEn/nOBWHGuVrKiartw5dZvA+SCIs8tR2U/zqxFasY6UXmL74Ly78925lLai+rP6yoBuPY6WWP15qtaJrKPDTRrIOHvsPM6KZ4/Fjc5UpvXp8qTNZtJeN8/r5tEcR5CpCoQQeO8kz9FTL9GdtPGfnaIC4WzRkMAoI9uylqJcAEcEtQuqRSwRf66BXZ/ufzeKYsXN0rfUwoTX9nNJRVeFDYMX6wCvmMs3EQOWpEkI8PbR0Ch3mgMV2YN4A58crsN5CaxmXGwMYBRFynNBKjQtajhpr2pp2ahLEz04Q73642i+yKz3M7I5EnV0+B9bdTbemKoQOHZ150cFTtgbnldxTUaLcmULgI70/pV6uTxologD9oxORDLhpxC3eNYWLjUA6jlMc7St6x9Zb9no1x2IOcL834uoWXSbgQEfxwvqqu+rySgzI1cD9HfV/pQk+wnSUCF/rYhv8VsWmhZf/HZaL/eNVfc3SqI37M3amvX35nczyM+NZtwnNxdtOGFUffkdZSObtQArsRq+1E5VZf1Sf48RHr8xT5plOfpNvD747qI+FVIq2+Tji5GHlAEsK5l+5V7EVANV8cTyUUcY+Y5ozfgXDA="
  - secure: "Ym277WT3X+kG+tDda+9gZvq/96gWHp3Xov8yCyznONlJLRbKimq+RfA4yulGmzYK0vKCRuN4/iC5WoZAfTR/qC0HTZydVz31R1zC7ycLQJI58L70eI9xQTLFbjbBEYWWZONLonxZHjlQFAxOvNSrfTs/kmmNufs2wWBisiUPIDCgnibW9LnfABmqwx5oXpXmLbOJpcGZ83IDE3WR2WTSqaCH1iRjio57Giguxzpbqjss8PspyMF4coF3NquQg+OiK4DHlihXLdSqpHQ1L+tXfiKwVq7GzzaPQX9mCp4D+cjJ3DKC+N6Rkno/49DxLra1qRhwIL98+JwK4BVxExhNXA5JWe97JegRFLtaKdOJ8yBfqgB0XVAOy4ZdBR0SolCinFNm6ayYjHJd0y0ZEcgoYHzFejF7gChhI/npGX5Qn0zDCOxupzHBJVVlR8JBwz3YOb4fdC7v1Xn0nqJZOkltTvjrphlPS/MWr3NarHg1WRYHKMlIsAJTc6F9UGavkzzKL/DTVA5qf3t0x3OHm3A5FT0/Xkgf49wJZGctOFWfKFYn98MySUk66mVonmsGw1NhF6b/RkFaBwB4WRlFOnm5K8VjU3Slj9POTEwXJYnlg2LQK3Wk22s5YvDgoE/u5en6Qq39N8YZ0OfUGj1dF1FOMXCRC5geLXY2HPTo94+S1Gc="