language: php
php:
- 7.0
script:
- php -l *.php
branches:
  only:
  - "/\\d\\.\\d\\.\\d/"
deploy:
  provider: script
  script: sh deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=http://plugins.svn.wordpress.org/gutenipsum/
  - secure: LSI+vlHnroPezlgHn3aG0+1bKZNcvfLrfQlZVRhshpRFzgKecrpCI8ArwGo2DKYMDIqqZpIPrrNQcylvInZmYdsdSPSiK4jzXvjrEuE5oFLOxGYXATPHuLDJ/PJmmI3MQbGNnxbxpa9R3UsCeZqkKuiclW8UxkRomoCmtbOjMkwbn6oms8Ye1MhLWHIioX0ULrtTcNURqTg9uXvwBzngkj+Mk94a+jN97vm4bhBczdq1C2OHnaJfs+9H+DFk8PK2Da1iRnpef+a17s0XM7E5gyBtBAOgqgrkNy6BQf11rkAHRE+4tXEUFenaEYOiJ5/VAVVr7OrwaKZyzfmXE70XXjOU9qHHOCTn4DzXhsYK/U/qvw386JoKl8/66amVlfl62eNrTCqUTd0zMn4rf9TvhT2Ba+m3MRhJ4xRJWDxsbtV5EIU3512Z8x0x36kAWNn5dVi16u3whzaLvqAa+EI5QL1fPcuI6HMEDR1dWsudavehUSPp/aoKv0oLy+cANwY3ZGI8RSLFHkhV2qqeZ8Mvtvyl1ozz27Ayl7B/5Igi3GXTDs2jj8AMP3JOpH7Sc8593qJHeGa0PaL3IGxa92G4wLxKx+/Wo9OnW9h7THTTj/IEdA4Li4b812hhxmifvCei8KtwVLA901Dmn+qLM7bQB3bBBEFFLiph6xRGj74Ju/w=
  - secure: I6YlPepqCjx7BO9JG2jquygPTxun+2RQMTiwzaY4QZmugo4glM5ZiWSFP3DMnBk5hjm/+pMNq/ihRIiPqehr85AHGKosuu26eixmqu+S6KtM1fsXkfVrxgXm7GFNGZg5B8czaQ8jLIgBSX9Sg4zbk4HFQYUxJWNF1lo5pDJxvrGMhI/TivKh9GUHAw/zD8fdatiY9Z0Ugm7zJSGPer5F2CyagfnEYKwmqX6keGPoFg2OgRKWxXhq/nAU873TWNxodVYbZ7v6bWdpFWcPOgivRGpx4TZ7uOpn0lG8g3zP1h+dpsBQwk69jXkiqWwrj++5OyoY7WBrBTGFjV16jGWlTfYtq3/CQCJ7NJa8feLKW96HGpNpkCQZNxFjePE7EWGJgxXzu+BbuQC7i8L3CvrbfbgFfPPxPihztlIOrhXzrJebFcFzlt/1jJlObUzw51XtKmXiGeJl/NC4E1Qm8OhZzzI4f33HdsdPxY3PYyPzBrRrSyKxFi+AO/N+1rLbO1PmGYDcPbDsoej69+9m8KR2GuEJQzlF14Z1MLYeoeCpiWCISoNh/D7juQ12HYZe3w6UnmQ2bMY/2neu0r/Qb5kNQaOc/9KnS7ddiuDqLh7USoRPGL0Nu4ZQtlaMRZ0GFukD6mLBx3E9qfBsfnsNyQ+NPQSMnqp8N5dP4SvTurKG4l8=
